topics:
-
  name    : align_teleop_combine
  topic   : /frcrobot_jetson/align_teleop_combine/swerve_drive_controller/cmd_vel
  timeout : 0.2
  priority: 100
-
  name    : align_pid
  topic   : /align_server/align_pid/swerve_drive_controller/cmd_vel
  timeout : 0.2
  priority: 100
-
  name    : teleop joystick comp
  topic   : /teleop/swerve_drive_controller/cmd_vel
  timeout : 0.2
  priority: 175
-
  name    : climber server
  topic   : /climber/swerve_drive_controller/cmd_vel
  timeout : 0.2
  priority: 150
-
  name    : outtake_hatch_panel_server
  topic   : /hatch_outtake/swerve_drive_controller/cmd_vel
  timeout : 0.2
  priority: 100
-
  name    : align_hatch
  topic   : /align_hatch/align_hatch/swerve_drive_controller/cmd_vel
  timeout : 0.2
  priority: 100
locks: []
